### ISSUE TITLE
rcnst error in dependencies

### ISSUE THREAD

**Issue by Enchufa2** [kalibera/cran-checks#3]
CRAN checks list a rcnst error for the `quantities` package, but the [rcnst report](https://github.com/kalibera/cran-checks/blob/master/rcnst/results/quantities/tests/testthat.Rout.fail) shows that the error happens in `dplyr`'s namespace. I believe that these errors should be attributed to the offending namespace, regardless of the package being checked.

**Comment by kalibera** [comment]
Yes, indeed it is very likely the true cause originates from `dplyr`, if you have a look at other reports you will see that many are related to `across_setup_impl` in `dplyr`, and one of the packages affected is also `dplyr`, so hopefully it will get fixed. It is known and documented that reports from these checks show affected packages, which are not always packages at fault. Note it won't be that easy to just report the package with the namespace where the functions with corrupted constants is, that namespace does not have to be at fault, either, figuring out reliably automatically which package is at fault is not possible.
